#!/bin/sh

sass --sourcemap=none source/simple-grid.scss:dist/my-simple-grid.css --style expanded 
sass --sourcemap=none source/simple-grid.scss:dist/my-simple-grid.min.css --style compressed

exit 0
